### ISSUE TITLE
Handling invalid countries names

### ISSUE THREAD

**Issue by Fady-Alwazir** [GSG-G11/fady_khaled_WorldGuide#38]

**Comment by Ibrahim-Jarada** [comment]
Just a try if you have a better solution go a had
    `       if(Array.isArray(response)){
        const [information] = response;
        const name = information.name.official;
        const capital = information.capital[0];
        const { population } = information;
        const roundedPopulation = (population / 1000000).toFixed(1);
        const image = information.flags.png;
        const map = information.maps.googleMaps;
      }else{
        const name = 'Not Found';
        const capital = 'Not Found';
        const roundedPopulation = 'Not Found';
        const image = "https://e7.pngegg.com/pngimages/829/733/png-clipart-logo-brand-product-trademark-font-not-found-logo-brand.png";
        const map = 'Not Found';

      }`
